apiVersion: v1
kind: Namespace
metadata:
  name: audio-demo
---
apiVersion: v1
kind: Service
metadata:
  name: audio-source
  namespace: audio-demo
spec:
  type: NodePort
  selector:
    app: audio-source
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-source
  namespace: audio-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-source
  template:
    metadata:
      labels:
        app: audio-source
    spec:
      containers:
        - name: audio-server
          image: audio-source:latest
          imagePullPolicy: Never  # For local development
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"