{{- if .Values.audioSource.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: audio-source
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "audio-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: audio-source
spec:
  type: {{ .Values.audioSource.service.type }}
  ports:
    - port: {{ .Values.audioSource.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.audioSource.service.type "NodePort") .Values.audioSource.service.nodePort }}
      nodePort: {{ .Values.audioSource.service.nodePort }}
      {{- end }}
  selector:
    {{- include "audio-lab.audioSourceSelectorLabels" . | nindent 4 }}
{{- end }}