{{- if and .Values.audioRelay.enabled (or .Values.audioRelay.ingress.enabled .Values.global.domain) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "audio-lab.fullname" . }}-audio-relay
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "audio-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: audio-relay
  {{- with .Values.audioRelay.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.audioRelay.ingress.className }}
  ingressClassName: {{ .Values.audioRelay.ingress.className }}
  {{- end }}
  {{- if .Values.global.domain }}
  tls:
    - hosts:
        - {{ printf "audio-relay.%s" .Values.global.domain | quote }}
      secretName: audio-relay-tls
  {{- else if .Values.audioRelay.ingress.tls }}
  tls:
    {{- range .Values.audioRelay.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.global.domain }}
    - host: {{ printf "audio-relay.%s" .Values.global.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: audio-relay
                port:
                  number: {{ .Values.audioRelay.service.port }}
    {{- else }}
    {{- range .Values.audioRelay.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: audio-relay
                port:
                  number: {{ $.Values.audioRelay.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}