# Default values for audio-lab
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Quick deployment with your domain (creates ingress automatically):
# helm install audio-lab . --set global.domain=audiolab.navicore.tech

# Global settings
global:
  namespace: audio-demo
  # Set this to your domain to enable ingress for both services
  # Example: helm install audio-lab . --set global.domain=audiolab.navicore.tech
  domain: ""

# Audio Source Service Configuration
audioSource:
  enabled: true
  replicaCount: 1
  
  image:
    repository: navicore/k8s-audio-audio-source
    pullPolicy: IfNotPresent
    # Defaults to chart appVersion, override with specific version
    tag: ""
  
  service:
    type: ClusterIP
    port: 8000
    nodePort: 30080  # Only used if type is NodePort
  
  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts:
      - host: audio-source.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

# Audio Relay Service Configuration
audioRelay:
  enabled: true
  replicaCount: 1
  
  image:
    repository: navicore/k8s-audio-audio-relay
    pullPolicy: IfNotPresent
    # Defaults to chart appVersion, override with specific version
    tag: ""
  
  service:
    type: ClusterIP
    port: 8001
    nodePort: 30081  # Only used if type is NodePort
  
  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts:
      - host: audio-relay.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  
  # Audio source URL configuration
  audioSourceUrl: "http://audio-source:8000"

# Common labels
commonLabels:
  app.kubernetes.io/part-of: audio-lab
  app.kubernetes.io/managed-by: helm

# Pod Security Context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Container Security Context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}