name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]  # Semantic versioning tags like v1.0.0
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [audio-source, audio-relay]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_HUB_USERNAME }}/k8s-audio-${{ matrix.service }}
        tags: |
          # Latest tag for main/master branch
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
          # Branch name for branch pushes
          type=ref,event=branch
          # PR number for pull requests
          type=ref,event=pr
          # Version tags - creates tags like 1.0.0 from v1.0.0
          type=semver,pattern={{version}}
          # Major.minor version - creates tags like 1.0 from v1.0.0
          type=semver,pattern={{major}}.{{minor}}
          # Major version - creates tags like 1 from v1.0.0
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          # SHA for every commit
          type=sha,format=short,prefix={{branch}}-

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SERVICE_NAME=${{ matrix.service }}
        cache-from: type=gha
        cache-to: type=gha,mode=max